services:
  postgres-dev:
    image: postgres:15-alpine
    container_name: beer4reactions-db-dev
    environment:
      POSTGRES_DB: Beer4ReactionsDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Beer4ReactionsDB_Dev"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_dev_data:
    driver: local
  dev_app_logs:
    driver: local

networks:
  default:
    name: beer4reactions-dev-network
